# Generated by Django 4.2.3 on 2023-07-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_resume'),
        ('core', '0003_category_alter_vacancy_options_vacancy_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vacancy',
            unique_together={('title', 'email')},
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=255, verbose_name='Название компании')),
                ('founding_date', models.DateField(verbose_name='Дата основания')),
                ('address_company', models.CharField(max_length=255, verbose_name='Адрес компании')),
                ('workers', models.ManyToManyField(blank=True, to='worker.worker')),
            ],
        ),
    ]
